spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinic
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: dominik04

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

